package org.dhbw.imbit11;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.io.StringWriter;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;


@WebServlet("/FileViewer")

/**
 * Loads master file (needs additional comments)
 * @author Mary
 * 
 */
public class FileViewer extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static File masterfile;

	/**
	 * Invokes the constructor of parent class (superclass) HttpServlet
	 */
	public FileViewer() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * Loads master file into the response and returns the character data to the client and
	 * gives out string generated by method prettyFormat
	 * 
	 * @param request - contains the request of a client
	 * @param response - contains the response with character encoding type of the masterfile
	 * 
	 * @throws IOException - throws exception when masterfile could not be loaded
	 */
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		request.setCharacterEncoding("UTF-8");
		
		try {
			URL urlToFile = this.getClass().getResource("masterfile.xml");
			masterfile = new File(urlToFile.toURI());
		} catch (Exception e) {
			System.err.println("Error loading masterfile.xml");
		}

		response.setContentType("text/html");
		PrintWriter out = response.getWriter();
		out.print(prettyFormat());
		
	}
	
	/**
	 * Defines stream and returns a string containing the input
	 * 
	 * @param input - input for the stream
	 * @param indent - specifies input file
	 * 
	 * @return string containing the input
	 * 
	 * @throws RuntimeException - throws all exception that occured
	 */
	public static String prettyFormat(String input, int indent) {
		try {
			Source xmlInput = new StreamSource(new StringReader(input));
			StringWriter stringWriter = new StringWriter();
			StreamResult xmlOutput = new StreamResult(stringWriter);
			TransformerFactory transformerFactory = TransformerFactory
					.newInstance();
			transformerFactory.setAttribute("indent-number", indent);
			Transformer transformer = transformerFactory.newTransformer();
			transformer.setOutputProperty(OutputKeys.INDENT, "yes");
			transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");

			transformer.transform(xmlInput, xmlOutput);
			return xmlOutput.getWriter().toString();
		} catch (Exception e) {
			throw new RuntimeException(e);
			// simple exception handling, please review it
		}
	}

	/**
	 * 
	 * @return string containing content of master file specified by indent
	 * 
	 * @throws IOException - throws exception when an IO error occured
	 */
	public  static String prettyFormat() throws IOException {
		return prettyFormat(readFileToString(), 2);
	}
	
	/**
	 * Gets the path of the masterfile.xml and reads out the content from the file as bytes
	 * and converts it into a string
	 * 
	 * @return content of the master file as string
	 * 
	 * @throws IOException - throws exception when an IO error occured
	 */
	private static String readFileToString() throws IOException {
		return new String(Files.readAllBytes(Paths.get(masterfile.toURI())));
	}

	/**
	 * (not in use in this method)
	 */
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

}
